# Generated by Django 5.1.4 on 2026-06-20 07:50

import apps.resumes.models
import apps.resumes.schema
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "edit_token",
                    models.CharField(
                        default=apps.resumes.models._new_token,
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="Untitled resume", max_length=200
                    ),
                ),
                ("data", models.JSONField(default=apps.resumes.schema.empty_resume)),
                ("template_id", models.CharField(default="classic", max_length=64)),
                (
                    "target_role",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry level / student"),
                            ("mid", "Mid level"),
                            ("senior", "Senior"),
                            ("exec", "Executive / leadership"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("job_description", models.TextField(blank=True, default="")),
                ("ats_score", models.JSONField(blank=True, null=True)),
                ("match_score", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variants",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CoverLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(blank=True, default="")),
                ("job_description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_letters",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
