# Generated by Django 5.1.4 on 2026-06-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="original_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
